services:
  server:
    container_name: golang_server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080" 
    # volumes:
    #   - ./server:/app 
    #   - /app/vendor 
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taskeeper
    depends_on:
      - database 
    command: ["./app"]
    restart: unless-stopped 

  database:
    container_name: postgres_db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskeeper
    volumes:
      - pg_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
